# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: momari <momari@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/11/10 22:42:00 by momari            #+#    #+#              #
#    Updated: 2024/02/22 09:53:33 by momari           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CFLALGS = -Wall -Wextra -Werror
NAME = libft.a
CC = cc
SRC = 	ft_isalpha.c ft_isdigit.c ft_isalnum.c ft_isascii.c 			\
		ft_isprint.c ft_strlen.c ft_memset.c ft_bzero.c 				\
		ft_memcpy.c ft_memmove.c ft_strlcpy.c ft_strlcat.c 				\
		ft_toupper.c ft_tolower.c ft_strchr.c ft_strrchr.c 				\
		ft_strncmp.c ft_memchr.c ft_memcmp.c ft_strnstr.c 				\
		ft_atoi.c ft_calloc.c ft_strdup.c ft_substr.c ft_strjoin.c 		\
		ft_strtrim.c ft_itoa.c ft_strmapi.c ft_striteri.c 				\
		ft_putchar_fd.c ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c 	\
		ft_split.c get_nline.c get_utils.c ft_lstnew_bonus.c 			\
		ft_lstadd_front_bonus.c ft_lstsize_bonus.c ft_lstlast_bonus.c 	\
		ft_lstadd_back_bonus.c ft_lstdelone_bonus.c ft_lstclear_bonus.c \
		ft_lstiter_bonus.c ft_lstmap_bonus.c

OBJS = $(SRC:.c=.o)
# BOBJS = $(BSRC:.c=.o)

all: $(NAME)

%.o: %.c libft.h
	$(CC) $(CFLALGS) -c $< -o $@

$(NAME): $(OBJS)
	ar rcs $@ $^

# bonus: $(BOBJS)
# 	ar rcs $(NAME) $(BOBJS)

clean:
	rm -rf $(OBJS)

fclean: clean
	rm -rf $(NAME)

re: fclean all

.PHONY : all clean fclean re bonus